### ISSUE TITLE
#ask

### ISSUE THREAD

**Issue by isfaaghyth** [isfaaghyth/seirama-web#1]
luq, rekening untuk donasi kemana luq? @luqni

**Comment by luqni** [comment]
A.N Muhammad Luqni Baehaqi

5976-01-010547-53-7

maaf fa baru bales...

2018-03-12 10:18 GMT+07:00 Muh Isfhani Ghiath <notifications@github.com>:

**Comment by isfaaghyth** [comment]
terima kasih beb, logo HD di tunggu eaaa

**Comment by luqni** [comment]
ih.. fast respon.. hehehe

kalah aku.. sama mastahku ini, padahal sibuk banget.. hihihi

2018-03-13 11:13 GMT+07:00 Muh Isfhani Ghiath <notifications@github.com>:

**Comment by isfaaghyth** [comment]
kebetulan ada notification di laptop ku wkwkw

**Comment by isfaaghyth** [comment]
logooo @luqni :(
